language: rust
sudo: required
rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc

after_script:
  - cd target; curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh

env:
  global:
    - secure: lnjK7UZppTbSAksdGe17sR4J2qkJlJ3fD2z3aRUGNXzEMnABuj5zOhPLsfsl7pld6HL4VEltMNqz7dv0R8EsFNSYOT7WIppyMcE6VGgw8YXXDJtn/LISAw7nSmpqBDSgP1TpufaOvzmnXFbuXG1h5qPdYolv7J4opjROH8cUPyz2hTQ9c7LpTHBtG+RjcxygOq2fBDhwj9vTxxDVnbyZNTeFPC/uifZaoGIaVefY0RlKmjKb6kJG/4zm+SYyKAduyviZf0rMbySBUWylHnMbywbqDCRGfRvKlMyNkbV0uAxTpCKZDzfiV3PcK5IiJqw4GPYMQVeHP1uWYPzVwHLHzZsSbtVvl33dPgw6S7pP8ZhTOkiu//G+gvIAZaBcsMznq2GJZoqDrZaSzpYVP/BTBiYiicyTzRrZlR8hB5pFeHjdaQZQRkrB9aFuibjwvn9vFYDKNbzXqjiqzpHODTEXMtsPhg6idvsp9lzVHoqZXOKCU6SG0Ex0aEcyrq8iEazKXtBQnKqmQyTOW9Vyb+WbgMeObgjyCs2of60rDsUwAvKa/KcR113XIC6m4KehmH17c18lgGCIS7Um8YxhFCs8f2diJUK67wt5Ze6nnSYuPKg7ynV/ER/FN8Iw2/kjwfkqwDgBrQ8fbOCAOxC0mw0QIs8U/dqBaoDRgx1NT5JgBhM=
