language: rust
rust: nightly
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc
after_script:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy-docs.sh
env:
  global:
    secure: ThKJkW8pemD1NIV0sNJH6NwVZWKGI7Zo+cVE2Qb2FC7BHeEV6EEAzXJBmYdUS10Ce+vT2iyJ59TARnO+XfDJvKPZrztOzTjy8pgREiUpDm0ASV+4LbO104OoB2PYxqLTE3/SJtymLDQa8wCFqa3XPUEjpmB7yK+WaApWZ0vjpqdBzFnVeSKKKe2/ayxSeIoeaUCDETxquGyJd5ls/jB5aaQTdEIIv336Z1pIn59B76oH5JS+qrsutAltfRDsMV3cL7EL2tqLQm6zIQ/iBD8mOI2TvoLn6rIliw7U/y+hIvKZRhk4W90IcaxdyY+oJoTB1ZRWSXSbyiXuAOQ/ap431gripgVSgNuqqOLVNkYkzLAvAjBBKvIyP/JyijS7Pa340DjKrZRRhN0DpnJjKacrXxTd/GtnJoFQFzgUkkNu67zGzOBcODlDcvr6pYJlc6PUt/1KRpVJjl5RzTohsN1Qbzv+sbhWXUHnSdiSI2TFLnQDocaYKNLu8u0y6I24wQnDUoYC7KuflQFXtNQuZeugVGcS4fgxlo+pGe66+AaEq3OdBcCzIsb700zuZycNEB8irgAhK2zo7Ms5DXCdUmLQzfrhL7cYMHXDLXrKAX4YXQMz6RoPtICa5Cvb5ign3/8NK1tsPjvqvPMUOdfnCe5sxILRtLBqi0SL3gQ0X5YnaNU=
